config/routes.rb
Cms::Application.routes.draw do

  devise_for :users, :controllers => {
    :sessions           => :sessions,
    :registrations      => :registrations,
  }

  resources :posts
  resources :roles
  resources :users

  resources :system_admins, :only => [:index]
  
  root :to => 'front#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user.can?(:show_post)
      can :show, "Post"
    end

    if user.can?(:create_post)
      can :create, "Post"
    end

    if user.can?(:edit_post)
      can :edit, "Post"
    end
    
    if user.can?(:delete_post)
      can :delete, "Post"
    end

  end

  #动态的根据authority来创建can?方法 
  Authority.all.each do |authority|
    split_pinyin = authority.pinyin.split("_")
    action_name, model_name  = split_pinyin.first, split_pinyin.last

    define_method("can_#{authority.pinyin}?") do |action|
      can "#{action_name}", model_name.upcase
    end
  end

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  # attr_accessible :title, :body

  belongs_to :authority
  belongs_to :role
  
end

app/models/authority.rb
class Authority < ActiveRecord::Base
   attr_accessible :name, :value, :pinyin

   has_many :assignments
   has_many :authorities, :through => :assignments
   
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :content, :display_status, :status, :user_id

  validates :title, presence: true

  STATUS_PUBLISHED = 1
  STATUS_HIDDEN    = 0

  DISPLAY_STATUS_MEMBER   = 1
  DISPLAY_STATUS_ALL      = 0

  paginates_per 20

  scope :published, where(status: STATUS_PUBLISHED)

end

app/models/role.rb
class Role < ActiveRecord::Base
   attr_accessible :name, :authority_ids

   has_many :assignments
   has_many :authorities, :through => :assignments

   has_many :users, :through => :user_roles
   has_many :user_roles

   after_save :caculate_authority

   private

   def caculate_authority
     authority_values = self.authorities.map(&:value).map(&:to_i).sum
     self.update_column(:authority, authority_values)
   end
   
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :role_ids

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :roles, :through => :user_roles
  has_many :user_roles

  #判断user自身的权限  和  所在的角色的权限
  def can?(authority_pinyin)
    authority = Authority.find_by_pinyin(authority_pinyin)
    authority_value = authority.value.to_i
    authority && (self.roles.map(&:authority).map(&:to_i).sum & authority_value) > 0
  end
  
end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url 
  end
end

app/controllers/front_controller.rb
class FrontController < ApplicationController
  def index
    @posts =  Post.published.page(params[:page])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #load_and_authorize_resource

  before_filter :authenticate_user!

  def index
    @posts =  Post.page(params[:page])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find params[:id]
  end

  def update
    @post = Post.find params[:id]
    if @post.update_attributes(params[:post])
      flash[:success] = t("post.success")
      redirect_to post_url(@post)
    else
      render edit_post_url(@post)
    end
  end

  def show
    @post = Post.find params[:id]
  end

  def create
    @post = Post.new(params[:post])
    @post.user_id = current_user.id

    if @post.save
      flash[:success] = t("post.success")
      redirect_to post_url(@post)
    else
      render :action => "new"
    end

  end

  def destroy
    post = Post.find params[:id]
    post.update_attributes(:status => Post::STATUS_HIDDEN)
    redirect_to posts_url 
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def new
    super
  end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  
  def index
    @roles = Role.page(params[:page])
  end

  def new
    @role = Role.new
  end

  def show
    @role = Role.find params[:id]
  end

  def edit
    @role = Role.find params[:id]
  end

  def create
    @role = Role.new(params[:role])

    if @role.save
      flash[:success] = t("list.success")
      redirect_to role_url(@role)
    else
      render :action => "new"
    end
  end

  def update
    @role = Role.find params[:id]
    if @role.update_attributes(params[:role])
      flash[:success] = t("role.success")
      redirect_to role_url(@role)
    else
      render edit_role_url(@role)
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController <  Devise::SessionsController

  def new
    super
  end

end

app/controllers/system_admins_controller.rb
class SystemAdminsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.page(params[:page])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update_attributes(params[:user])
      flash[:success] = t("user.success")
      redirect_to user_url(@user)
    else
      render :action => "edit" 
    end
  end

  def show
    @user = User.find params[:id]
  end

  def create
    @user = User.new(params[:user])
    encrypt_new = ::BCrypt::Password.create(params[:user][:password]).to_s
    @user.encrypted_password = encrypt_new

    if @user.save
      flash[:success] = t("user.success")
      redirect_to user_url(@user)
    else
      render :action => "new"
    end

  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/front_helper.rb
module FrontHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/system_admins_helper.rb
module SystemAdminsHelper
end

app/views/front/index.html.erb
<style type="text/css">
  .container{ width:100%;}
</style>


<table class="table table-striped">
  <tbody>
    <% if current_user.blank? %>
      <%= render_cell :post, :not_member_posts%>
    <% else %>
      <%= render_cell :post, :all_posts %>
    <% end %>

  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cms</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'share/top'%>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :content, :class => 'text_area' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label "只有会员才能看到", :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :display_status %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                posts_path, :class => 'btn' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @posts && @posts.each do |post| %>
      <tr>
        <td><%= link_to post.id, post_path(post) %></td>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.created_at.to_s(:db) %></td>
        <td>
          <% if current_user.can?(:edit_post)%>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_post_path(post), :class => 'btn btn-mini' %>
          <% end %>

            <% if current_user.can?(:delete_post)%>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                post_path(post),
                :method => :delete,
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-mini btn-danger' %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if current_user.can?(:create_post)%>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_post_path,
            :class => 'btn btn-primary' %>
<% end %>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @post.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @post.content %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @post.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @post.status %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              posts_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_post_path(@post), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              post_path(@post),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/roles/_form.html.erb
<%= form_for @role, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <%= render_cell :authority, :all_role_authorities, :role => @role %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                roles_path, :class => 'btn' %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<%- model_class = Role -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/roles/index.html.erb
<%- model_class = Role -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:authority) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= link_to role.id, role_path(role) %></td>
        <td><%= role.name %></td>
        <td><%= role.authority %></td>
        <td><%=l role.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_role_path(role), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      role_path(role),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_role_path,
            :class => 'btn btn-primary' %>

app/views/roles/new.html.erb
<%- model_class = Role -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/roles/show.html.erb
<%- model_class = Role -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @role.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:authority) %>:</strong></dt>
  <dd><%= @role.authority %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              roles_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_role_path(@role), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              role_path(@role),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/share/_top.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container-fluid">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="#">CMS</a>
      <div class="nav-collapse collapse">
        <% if user_signed_in? %>
          <p class="navbar-text pull-right">
          welcome, <%= current_user.email %>
          <%= link_to "logout", destroy_user_session_path, :method => :delete %>
          <%= link_to "system_admin", system_admins_path %>
          </p>
        <% else %>
          <p class="navbar-text pull-right">
          <%= link_to "register", new_user_registration_path %> or <%= link_to "login", new_user_session_path %>
          </p>
        <% end %>
        <ul class="nav">
          <li class="active"><a href="<%= root_path %>">Home</a></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/system_admins/index.html.erb
<style type="text/css">
  .system {
    padding:10px;
    width:80%;
    overflow: hidden;
    margin-bottom: 30px;
    font-size: 14px;
    font-weight: 200;
    line-height: 30px;
    background-color: #fff;
  }
  .system ul {  width:99%; margin:0; border:2px solid #ccc; overflow:hidden; }
  .system li { list-style:none; float:left; width:25%; height:30px;
               text-align:center; line-height: 30px; margin-bottom:5px; }
  .admin_tool { background-color: #f0f0f0; }
</style>
<div class="system">
  <div>
    <h5>系统管理</h5>
    <ul>
      <li class="admin_tool"><a href="<%= posts_path%>" >帖子管理</a></li>
      <li>管理用户账号和密码</li>
      <li class="admin_tool"><a href="<%= users_path%>" >用户管理</a></li>
      <li>管理用户账号和密码</li>
      <li class="admin_tool"><a href="<%= roles_path%>" >角色管理</a></li>
      <li>角色管理</li>
    </ul>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <% Role.all.each do |role| %>
      <%= check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role) %>
      <%= role.name %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.email %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>